name: EPG Cron Update

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: epg-job
  cancel-in-progress: true

jobs:
  epg-job:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      (
        github.event_name == 'push' &&
        contains(github.event.head_commit.message, '[update epg]')
      )

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Required for auto-commit to work correctly on some triggers
          persist-credentials: true 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          check-latest: true

      - name: Setup Dev Proxy
        id: setup-devproxy
        uses: dev-proxy-tools/actions/setup@v1
        with:
          version: v1.0.0

      - name: Start EPG
        env:
          PROXY_URL: ${{ steps.setup-devproxy.outputs.proxy-url }}
        run: |
          chmod +x ./update_epg.sh
          ./update_epg.sh || true
      
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes (if any)
        continue-on-error: true
        run: |
          git add -A

          git diff --cached --quiet && echo "No changes" && exit 0

          git commit -m "chore: update epg"

      - name: Sync with remote
        continue-on-error: true
        run: |
          git fetch origin "${{ github.ref_name }}"
          git pull origin ${{ github.ref_name }} --rebase

      - name: Push changes safely
        continue-on-error: true
        run: |
          git push origin HEAD:${{ github.ref_name }}
          
      - name: Build pages
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: static.yml
