name: Stream Status Check

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      (
        github.event_name == 'push' &&
        contains(github.event.head_commit.message, '[update streams]')
      )

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # IMPORTANT: full history
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          check-latest: true

      - name: Run stream checker
        run: |
          pip install aiohttp aiodns
          python stream_status.py --concurrency 20 --timeout 10 --out status.json
      
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes (if any)
        run: |
          git add -A

          git diff --cached --quiet && echo "No changes" && exit 0

          git commit -m "chore: update status"

      - name: Sync with remote
        continue-on-error: true
        run: |
          git fetch origin "${{ github.ref_name }}"
          git pull origin ${{ github.ref_name }} --rebase

      - name: Push changes safely
        run: |
          git push origin HEAD:${{ github.ref_name }}