name: Thumbnail Saver

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

concurrency:
  group: thumbnail-job
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      (
        github.event_name == 'push' &&
        contains(github.event.head_commit.message, '[update thumbnails]')
      )

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install numpy pillow tqdm psutil av

      - name: Run Thumbnail Generator
        run: |
          python thumbnail.py
          python thumbnails_content.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit & Force Push (NO CONFLICTS)
        run: |
          git add -A

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "chore: update thumbnails"
          git push origin HEAD:${{ github.ref_name }} --force
